language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
sudo: false
env:
  - MONGODB_VERSION=2.2.x
  - MONGODB_VERSION=2.4.x
  - MONGODB_VERSION=2.6.x
  - MONGODB_VERSION=3.0.x
  - MONGODB_VERSION=3.2.x
  - MONGODB_VERSION=3.3.x
