sudo: required
dist: trusty
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

env:
  - MONGODB_VERSION=2.6.x
  - MONGODB_VERSION=3.0.x
  - MONGODB_VERSION=3.2.x
  - MONGODB_VERSION=3.4.x
