baseurl = "http://mongodb.github.io"
MetaDataFormat = "yaml"
title = "MongoDB 2.0.0 Driver"

[indexes]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "api"
    pre = "<i class='fa fa-file-text'></i>"
    url = "api-docs/index.html"
    weight = -90
[[menu.main]]
    name = "driver portal"
    pre = "<i class='fa fa-file-text'></i>"
    url = "http://learnmongodbthehardway.com/"
    weight = -115
[[menu.main]]
    name = "Mongo DB Docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "http://mongodb.org"
    weight = -113
[[menu.main]]
    name = "legacy docs 1.4.X"
    pre = "<i class='fa fa-file-text'></i>"
    url = "#REPLACE/1.4"
    weight = -110
[[menu.main]]
    name = "about driver"
    pre = "<i class='fa fa-gift'></i>"
    weight = -105
    identifier = "about"
[[menu.main]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
[[menu.main]]
    name = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -40
[[menu.main]]
    name = "articles"
    pre = "<i class='fa fa-book'></i>"
    weight = -30
[[menu.main]]
    name = "community"
    pre = "<i class='fa fa-group'></i>"
    weight = -60
