baseurl = "http://mongodb.github.io"
MetaDataFormat = "yaml"
title = "MongoDB 2.0.0 Driver"

[indexes]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "API Docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "/api/index.html"
    weight = -114
[[menu.main]]
    name = "about driver"
    pre = "<i class='fa fa-gift'></i>"
    weight = -105
    identifier = "about"
[[menu.main]]
    name = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -40
[[menu.main]]
    name = "articles"
    pre = "<i class='fa fa-book'></i>"
    weight = -30
[[menu.main]]
    name = "community"
    pre = "<i class='fa fa-group'></i>"
    weight = -10
[[menu.main]]
    name = "Related"
    identifier = "related"
    pre = "<i class='fa fa-group'></i>"
    weight = -10
[[menu.main]]
    parent = "related"
    name = "1.1 Core Docs"
    pre = "<i class='fa fa-group'></i>"
    weight = -10
[[menu.main]]
    parent = "related"
    name = "1.1 Core Docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "http://mongodb.github.com/node-mongodb-native/core"
    weight = -10
[[menu.main]]
    parent = "related"
    name = "driver portal"
    pre = "<i class='fa fa-file-text'></i>"
    url = "http://mongodb.github.io/node-mongodb-native/"
    weight = -115
[[menu.main]]
    parent = "related"
    name = "Mongo DB Docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "http://mongodb.org"
    weight = -112

